### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by eman1986** [wstaelens/TypeScript-Summernote#4]
This is great that you made a typescript definition for summernote, curious if you could make this a npm package for easy fetching?

**Comment by wstaelens** [comment]
@eman1986 i think I don't have time for it, maybe you can create one for it. (never actually created a npm).

**Comment by eman1986** [comment]
I can, I've done it before

**Comment by typeofweb** [comment]
@eman1986 did you do it?

**Comment by eman1986** [comment]
not yet no, I can though if the demand is there

**Comment by wstaelens** [comment]
or you create demand by publishing it ;-)

**Comment by eman1986** [comment]
I'll do it tonight

**Comment by eman1986** [comment]
there is now an npm package:

https://www.npmjs.com/package/summernote-typescript
