### ISSUE TITLE
Any plan to push this to DefinitelyTyped repo?

### ISSUE THREAD

**Issue by dharijanto** [wstaelens/TypeScript-Summernote#5]
Hi, first of all, thanks a bunch for sharing this.

Secondly, do you have plan to submit this to DefinitelyTyped repo? If not, I can do that :)

More people would definitely be helped by this definition.

@wstaelens 

Thanks

**Comment by wstaelens** [comment]
feel free to do it, as I don't plan it/don't have time for it ;-)

**Comment by dharijanto** [comment]
Awesome, I'll do that :)

**Comment by eman1986** [comment]
I already did it

**Comment by eman1986** [comment]
I made a npm package for this

https://www.npmjs.com/package/summernote-typescript

**Comment by wstaelens** [comment]
Thanks!

**Comment by dharijanto** [comment]
Nah, I didn't mean separate npm package. I meant DefinitelyTyped package, just like most of the other packages. (i.e. people can just ```npm install @types/summernote```)

**Comment by dharijanto** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26874

Pull-request is on going review :)

**Comment by dharijanto** [comment]
Type definition is merged, now people can just ```npm install -D @types/summernote```

Thanks again for the original work on the definition :)
